### PR TITLE
fix(components): `gs-location-filter`: show better error

### LINKED ISSUE #75: Location filter: Properly handle error when fetching autocomplete data
Currently, it looks like this when the LAPIS call fails:

grafik

What should we display instead?

### PR DESCRIPTION
**Pull request by fengelniederhammer**
resolves #75

### Summary

Show the error message from LAPIS when the call to fetch the autocomplete list fails. The error details are shown in a separate modal.

### Screenshot

grafik

### PR Checklist

- ~~[ ] All necessary documentation has been adapted.~~
- [x] The implemented feature is covered by an appropriate test.

### CODE REVIEW

File: components/src/preact/components/error-display.tsx [hunk 1]
```diff
@@ -10,11 +14,36 @@ export class UserFacingError extends Error {
...
         <div className='h-full w-full rounded-md border-2 border-gray-100 p-2 flex items-center justify-center flex-col'>
             <div className='text-red-700 font-bold'>Error</div>
-            <div>Oops! Something went wrong.</div>
-            {error instanceof UserFacingError && <div className='text-sm text-gray-600'>{error.message}</div>}
+            <div>
+                Oops! Something went wrong.
+                {error instanceof UserFacingError && (
+                    <>
+                        {' '}
+                        <button className='text-sm text-gray-600' onClick={() => ref.current?.showModal()}>
```
Comment (JonasKellerer) [inline components/src/preact/components/error-display.tsx:27]:
```suggestion
                        <button className='text-sm text-gray-600 hover:text-gray-300' onClick={() => ref.current?.showModal()}>
```
So you see more clearly that you can click this.

**Review by JonasKellerer — APPROVED** [review]
Nice. LGTM
