### PR TITLE
fix(components): show an info element on mutation filter #157

### LINKED ISSUE #157: Mutation filter: question mark
Show a question mark that provide additional information about the mutation filter syntax

### PR DESCRIPTION
**Pull request by JonasKellerer**
resolves #157

### Summary

Shows an info element on the mutation filter and adds examples on the placeholder text.

### Screenshot

grafik

### PR Checklist

~~- [ ] All necessary documentation has been adapted.~~
~~- [ ] The implemented feature is covered by an appropriate test.~~

### CODE REVIEW

File: components/src/preact/mutationFilter/mutation-filter.tsx [hunk 1]
```diff
@@ -83,11 +84,14 @@ export const MutationFilter: FunctionComponent<MutationFilterProps> = () => {
...
-                setSelectedFilters={setSelectedFilters}
-                fireChangeEvent={fireChangeEvent}
-            />
+            <div class='flex justify-between'>
+                <SelectedMutationDisplay
+                    selectedFilters={selectedFilters}
+                    setSelectedFilters={setSelectedFilters}
+                    fireChangeEvent={fireChangeEvent}
+                />
+                <Info className='mx-1' content='Info for mutation filter' />
```
Comment (fengelniederhammer) [inline components/src/preact/mutationFilter/mutation-filter.tsx:93]: Let's add another issue as a reminder to fill this with some proper information text.

**Review by fengelniederhammer — APPROVED** [review]

File: components/src/preact/mutationFilter/mutation-filter.tsx (hunk 1 above)
Comment (JonasKellerer) [reply components/src/preact/mutationFilter/mutation-filter.tsx:93]: Good idea: #182
